
name: CI / Build & Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ backend, frontend ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shehab-${{ matrix.service }}-algotask:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/shehab-${{ matrix.service }}-algotask:${{ github.sha }}
      - name: Smoke-test backend
        if: matrix.service == 'backend'
        run: |
          docker run -d --name backend-test \
            -e DB_HOST=host.docker.internal \
            -e DB_USER=$DB_USER \
            -e DB_PASS=$DB_PASS \
            -e DB_NAME=$DB_NAME \
            -p 5000:5000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/shehab-backend:${{ github.sha }}
          for i in {1..10}; do
            curl --fail http://localhost:5000/api/data && break
            echo "waiting for backend…"
            sleep 3
          done
        env:
          DB_USER: appuser
          DB_PASS: AppPass123!
          DB_NAME: testdb


